#!/usr/bin/env perl

use strict;
use warnings;
use diagnostics;

use utf8;
use locale;
use POSIX qw(locale_h);
my $locale = 'ru_RU.UTF-8';
my $new_locale = setlocale(LC_ALL, $locale);
die "att: no locale $locale" if ($new_locale ne $locale);
binmode STDOUT, ":utf8";
use encoding "utf8";

use MMigration;
use Data::Dumper;
use PageCreator;
use GetConfInfo;
use ComponentCreator;
use GetParam;
use List;
use SetParam;
use GetParam;

our $r = shift;# apache data request
our $m = MMigration->new($r);

my $dbh=$m->dbRole('apuser');#берем роль, пока самую простуюдля извлечения данных


my $path = $ENV{'PATH_INFO'};
$path ||= '';

my $pageConf = 0;
if ($path =~ /\/(\d+)\/index.html$/)
{
    $pageConf = $1;
}
my  $GI=GetConfInfo->new($pageConf,$dbh,$m,$r);
my  $params=$GI->getParam();
my  $rendered={};
    $params->{'rendered'}=$rendered;




my  $PC=PageCreator->new($params);


$m->print($PC->output());


=for nobodies
my $sp=SetParam->new($dbh,$m);
my  @arr=(1..5);
    $arr[0]={};        
    $arr[1]={};
    $arr[2]={};        
    $arr[3]={};    
    $arr[4]={};
    $arr[0]->{'href'}="#";
    $arr[0]->{'text'}="Установка оборудования";
    $arr[0]->{'imagehref'}="/images/hard60.jpg";
    $arr[1]->{'href'}="#";
    $arr[1]->{'text'}="Администрирование сетей";
    $arr[1]->{'imagehref'}="/images/comm60.jpg";
    $arr[2]->{'href'}="#";
    $arr[2]->{'text'}="Программное обеспечение";
    $arr[2]->{'imagehref'}="/images/code80.jpg";
    $arr[3]->{'href'}="#";
    $arr[3]->{'text'}="Привет всем!";
    $arr[3]->{'imagehref'}="/images/code80.jpg";
    $arr[4]->{'href'}="#";
    $arr[4]->{'text'}="Чтоб ты был здоров!";
    $arr[4]->{'imagehref'}="/images/comm60.jpg";
my  $id=$sp->setArray(\@arr);
    warn "ID = $id";
=cut


=for nobody

main
<html>
<head><title>test</title></head>
<body>
<!--News/-->
</body>
</html>

end
=cut
